using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace AOP.Logging.SourceGenerator;

/// <summary>
/// Source generator that creates logging wrappers for classes and methods decorated with logging attributes.
/// </summary>
[Generator]
public class LoggingSourceGenerator : IIncrementalGenerator
{
    private const string LogClassAttribute = "AOP.Logging.Core.Attributes.LogClassAttribute";
    private const string LogMethodAttribute = "AOP.Logging.Core.Attributes.LogMethodAttribute";

    /// <summary>
    /// Equality comparer for ClassDeclarationSyntax based on syntax tree and span.
    /// Used for deduplication when a class has both LogClass and LogMethod attributes.
    /// </summary>
    private sealed class ClassDeclarationSyntaxComparer : IEqualityComparer<ClassDeclarationSyntax>
    {
        public static readonly ClassDeclarationSyntaxComparer Instance = new ClassDeclarationSyntaxComparer();

        public bool Equals(ClassDeclarationSyntax? x, ClassDeclarationSyntax? y)
        {
            if (ReferenceEquals(x, y)) return true;
            if (x is null || y is null) return false;
            return x.SyntaxTree == y.SyntaxTree && x.Span == y.Span;
        }

        public int GetHashCode(ClassDeclarationSyntax obj)
        {
            if (obj is null) return 0;
            unchecked
            {
                return (obj.SyntaxTree.GetHashCode() * 397) ^ obj.Span.GetHashCode();
            }
        }
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all classes with LogClass attribute using ForAttributeWithMetadataName for better performance
        var classesWithLogClass = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                LogClassAttribute,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.TargetNode);

        // Find all methods with LogMethod attribute and get their containing classes
        var classesWithLogMethod = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                LogMethodAttribute,
                predicate: static (node, _) => node is MethodDeclarationSyntax,
                transform: static (ctx, _) =>
                {
                    // Get the containing class of the method
                    var method = (MethodDeclarationSyntax)ctx.TargetNode;
                    return method.FirstAncestorOrSelf<ClassDeclarationSyntax>();
                })
            .Where(static c => c is not null);

        // Combine both sources efficiently: Concat before Collect to reduce allocations
        var allClasses = classesWithLogClass
            .Concat(classesWithLogMethod!)
            .Collect();

        // Combine with compilation
        var compilationAndClasses = context.CompilationProvider.Combine(allClasses);

        // Generate the logging code
        context.RegisterSourceOutput(compilationAndClasses,
            static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    private static void Execute(
        Compilation compilation,
        ImmutableArray<ClassDeclarationSyntax?> classes,
        SourceProductionContext context)
    {
        if (classes.IsDefaultOrEmpty)
        {
            return;
        }

        // Deduplicate classes that have both LogClass and LogMethod attributes
        // Using Distinct with custom comparer is more efficient than manual HashSet approach
        var uniqueClasses = classes
            .Where(c => c is not null)
            .Distinct(ClassDeclarationSyntaxComparer.Instance);

        // Generate code for each unique class
        foreach (var classDeclaration in uniqueClasses)
        {
            context.CancellationToken.ThrowIfCancellationRequested();

            var semanticModel = compilation.GetSemanticModel(classDeclaration!.SyntaxTree);
            var classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);

            if (classSymbol is null)
            {
                continue;
            }

            var source = GenerateLoggingCode(classSymbol, classDeclaration);
            context.AddSource($"{classSymbol.Name}_Logging.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string GenerateLoggingCode(INamedTypeSymbol classSymbol, ClassDeclarationSyntax classDeclaration)
    {
        var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
        var className = classSymbol.Name;
        var hasLogClassAttribute = classSymbol.GetAttributes()
            .Any(a => a.AttributeClass?.ToDisplayString() == LogClassAttribute);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Diagnostics;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine("using AOP.Logging.Core.Interfaces;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"    partial class {className}");
        sb.AppendLine("    {");
        sb.AppendLine("        private IMethodLogger? __methodLogger;");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Sets the method logger for AOP logging.");
        sb.AppendLine("        /// This is typically called by the DI container.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public void SetMethodLogger(IMethodLogger methodLogger)");
        sb.AppendLine("        {");
        sb.AppendLine("            __methodLogger = methodLogger;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
