using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace AOP.Logging.SourceGenerator;

/// <summary>
/// Source generator that creates logging wrappers for classes and methods decorated with logging attributes.
/// </summary>
[Generator]
public class LoggingSourceGenerator : IIncrementalGenerator
{
    private const string LogClassAttribute = "AOP.Logging.Core.Attributes.LogClassAttribute";
    private const string LogMethodAttribute = "AOP.Logging.Core.Attributes.LogMethodAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all classes with LogClass attribute using ForAttributeWithMetadataName for better performance
        var classesWithLogClass = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                LogClassAttribute,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => (ClassDeclarationSyntax)ctx.TargetNode);

        // Find all methods with LogMethod attribute and get their containing classes
        var classesWithLogMethod = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                LogMethodAttribute,
                predicate: static (node, _) => node is MethodDeclarationSyntax,
                transform: static (ctx, _) =>
                {
                    // Get the containing class of the method
                    var method = (MethodDeclarationSyntax)ctx.TargetNode;
                    return method.FirstAncestorOrSelf<ClassDeclarationSyntax>();
                })
            .Where(static c => c is not null);

        // Combine both sources
        var allClasses = classesWithLogClass
            .Collect()
            .Combine(classesWithLogMethod.Collect());

        // Combine with compilation
        var compilationAndClasses = context.CompilationProvider.Combine(allClasses);

        // Generate the logging code
        context.RegisterSourceOutput(compilationAndClasses,
            static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    private static void Execute(
        Compilation compilation,
        (ImmutableArray<ClassDeclarationSyntax> Left, ImmutableArray<ClassDeclarationSyntax?> Right) classes,
        SourceProductionContext context)
    {
        // Combine both sources and deduplicate based on syntax tree and span
        var seenClasses = new HashSet<(SyntaxTree, TextSpan)>();
        var uniqueClasses = new List<ClassDeclarationSyntax>();

        // Process classes with LogClass attribute
        foreach (var classDecl in classes.Left)
        {
            var key = (classDecl.SyntaxTree, classDecl.Span);
            if (seenClasses.Add(key))
            {
                uniqueClasses.Add(classDecl);
            }
        }

        // Process classes with LogMethod attribute
        foreach (var classDecl in classes.Right)
        {
            if (classDecl is null)
            {
                continue;
            }

            var key = (classDecl.SyntaxTree, classDecl.Span);
            if (seenClasses.Add(key))
            {
                uniqueClasses.Add(classDecl);
            }
        }

        // Generate code for each unique class
        foreach (var classDeclaration in uniqueClasses)
        {
            context.CancellationToken.ThrowIfCancellationRequested();

            var semanticModel = compilation.GetSemanticModel(classDeclaration.SyntaxTree);
            var classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);

            if (classSymbol is null)
            {
                continue;
            }

            var source = GenerateLoggingCode(classSymbol, classDeclaration);
            context.AddSource($"{classSymbol.Name}_Logging.g.cs", SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string GenerateLoggingCode(INamedTypeSymbol classSymbol, ClassDeclarationSyntax classDeclaration)
    {
        var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
        var className = classSymbol.Name;
        var hasLogClassAttribute = classSymbol.GetAttributes()
            .Any(a => a.AttributeClass?.ToDisplayString() == LogClassAttribute);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Diagnostics;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine("using AOP.Logging.Core.Interfaces;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"    partial class {className}");
        sb.AppendLine("    {");
        sb.AppendLine("        private IMethodLogger? __methodLogger;");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Sets the method logger for AOP logging.");
        sb.AppendLine("        /// This is typically called by the DI container.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public void SetMethodLogger(IMethodLogger methodLogger)");
        sb.AppendLine("        {");
        sb.AppendLine("            __methodLogger = methodLogger;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
